name: 'Setup Misc Configs'
description: 'Set up kernel configuration fragment with miscellaneous options'

runs:
  using: "composite"
  steps:
    - name: Enable Kernel Configs
      uses: ./.github/actions/set-kernel-config
      with:
        config_list: |
          CONFIG_OVERLAY_FS=y
          CONFIG_TMPFS_XATTR=y
          CONFIG_TMPFS_POSIX_ACL=y
          CONFIG_HAVE_SYSCALL_TRACEPOINTS=y
          CONFIG_HAVE_ARCH_SECCOMP_FILTER=y
          CONFIG_SECCOMP_FILTER=y
          CONFIG_FTRACE=y
          CONFIG_FUNCTION_TRACER=y
          CONFIG_DYNAMIC_FTRACE=y
          CONFIG_USER_NS=y
          CONFIG_UTS_NS=y
          CONFIG_NET_NS=y
          CONFIG_NAMESPACES=y
          CONFIG_IPC_NS=y
          CONFIG_CGROUPS=y
          CONFIG_CGROUP_DEVICE=y
          CONFIG_BRIDGE=y
          CONFIG_VETH=y
          CONFIG_TMPFS_XATTR=y
          CONFIG_TMPFS_POSIX_ACL=y
          CONFIG_ZSMALLOC=y
          CONFIG_ZRAM=y
          CONFIG_SCHED_AUTOGROUP=y
          # CONFIG_HZ_300 is not set
          # CONFIG_PANIC_ON_OOPS is not set
          # CONFIG_SLUB_DEBUG is not set
          CONFIG_IKCONFIG=y
          CONFIG_IKCONFIG_PROC=y
          CONFIG_INPUT_KEYCOMBO=y
          CONFIG_BLK_WBT=y
          CONFIG_BLK_WBT_MQ=y
          CONFIG_COMPACTION=y
          CONFIG_SCHED_MC=y
          # CONFIG_PREEMPT_VOLUNTARY=y is intentionally not set (choice symbol, use GKI default)
          CONFIG_STATIC_USERMODEHELPER=y
          CONFIG_KALLSYMS=y
          CONFIG_KALLSYMS_ALL=y
